# example values

server:
  port: 8080
  ssl:
    keyStoreType: PKCS12
    key-store: /home/progforce/NewMedicalService/src/main/resources/keystore/certificateMS.p12
    key-store-password: ENC(BVN7v6x+lYVu1GyR3ymw5w==)


# https://www.springcloud.io/post/2022-04/spring-samesite/#gsc.tab=0
  servlet:
    session:
      cookie:
        same-site: None
        secure: true



jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD:secretKey}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


spring:
  mail:
    host: mail.smtp2go.com
    port: 2525
    username: progforce.com
    #password: Fmx0d0TB90IKfMQM
    password: ENC(M7W1SF5PZD0SD0w3B2aq/C2I5r3mKHsJJqHwMqPlBfk=)
  datasource:
    username: root
    password: ENC(w7qYbKTj2l8T6ozrMwNQYpvJbVSQjUzG)
    #password: password
    #url: jdbc:mysql://localhost:3306/medical_service?serverTimezone=Europe/Moscow
    url: jdbc:mysql://localhost:3306/medical_service?useSSL=false&serverTimezone=Europe/Moscow
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  main:
    allow-circular-references: true


templates:
  contract: /home/progforce/Temp/MedicalService/1/templateContract.pdf
  agreement: /home/progforce/Temp/MedicalService/1/templateAgreement.pdf
  questionnaire: /home/progforce/Temp/MedicalService/1/templateQuestionnaire.pdf

mail:
  enabled: true
  from: vitaly.gusev@progforce.com
  preLink: http://localhost:3000/documents/
  subject: כשלון בריצת ממשק מניפה ארכיב



